version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network

  web:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgre:567234@db:5432/hw02 #postgres://postgres:567234@db:5432/fastapi_db
    depends_on:
      - db
    networks:
      - fastapi_network

networks:
  fastapi_network:

volumes:
  postgres_data:
